// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0vHxRd625Y4EtZTQoaSLOy2Hhal-3C8Q',
    appId: '1:740142303271:web:5e9d331e9e168078096602',
    messagingSenderId: '740142303271',
    projectId: 'skill-sharing-f5e79',
    authDomain: 'skill-sharing-f5e79.firebaseapp.com',
    storageBucket: 'skill-sharing-f5e79.firebasestorage.app',
    measurementId: 'G-6R95LBCGHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvxZRqwC8ZLHnGvmsqcHQy4swjCpT4y-Q',
    appId: '1:740142303271:android:9c61dc63cea8fc05096602',
    messagingSenderId: '740142303271',
    projectId: 'skill-sharing-f5e79',
    storageBucket: 'skill-sharing-f5e79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS5C1s5FUGIpPaLfQySx3kRyqi-UL6Fdo',
    appId: '1:740142303271:ios:eb82c879588a57eb096602',
    messagingSenderId: '740142303271',
    projectId: 'skill-sharing-f5e79',
    storageBucket: 'skill-sharing-f5e79.firebasestorage.app',
    iosBundleId: 'com.example.skillswap1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS5C1s5FUGIpPaLfQySx3kRyqi-UL6Fdo',
    appId: '1:740142303271:ios:eb82c879588a57eb096602',
    messagingSenderId: '740142303271',
    projectId: 'skill-sharing-f5e79',
    storageBucket: 'skill-sharing-f5e79.firebasestorage.app',
    iosBundleId: 'com.example.skillswap1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0vHxRd625Y4EtZTQoaSLOy2Hhal-3C8Q',
    appId: '1:740142303271:web:08d3e09d929f6a5d096602',
    messagingSenderId: '740142303271',
    projectId: 'skill-sharing-f5e79',
    authDomain: 'skill-sharing-f5e79.firebaseapp.com',
    storageBucket: 'skill-sharing-f5e79.firebasestorage.app',
    measurementId: 'G-KQ9S9PMD8W',
  );
}
